name: ml_summer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scikit-learn>=1.1.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - openpyxl>=3.0.0
  - pathlib2>=2.3.0
  - pip
  - pip:
    - myutils 